# Generated by Django 4.1.7 on 2023-03-08 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=40)),
                ("birth_date", models.DateField()),
                ("has_pet", models.BooleanField(default=True)),
                ("number_pet", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ImageProfile",
            fields=[
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="polls.person",
                    ),
                ),
                ("image", models.URLField()),
            ],
        ),
    ]
