# Generated by Django 4.1.7 on 2023-03-08 08:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0002_post_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="polls.person",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="released_date",
            field=models.DateField(
                default=datetime.datetime(2023, 3, 8, 12, 7, 38, 256273)
            ),
        ),
    ]
